### ISSUE TITLE
User Story 60, Admin is redirected from Merchant Dashboard to User profile

### ISSUE THREAD

**Issue by memcmahon** [BrennanAyers/little_shop#23]
```
As an admin user
If I visit a merchant dashboard, but that merchant is a regular user
Then I am redirected to the appropriate user profile page.

eg, if I visit "/admin/merchants/7" but that merchant is a regular user
then I am redirected to "/admin/users/7" and see their user profile page
```

### Checklist:

- [x] base tests are written
- [x] base code is written to pass tests
- [x] edge case ("sad path") tests written (if required)
- [x] edge case code written (if required)
- [ ] code is reviewed
- [ ] branch is merged
- [ ] all tests still pass

child of #208

child of #274

**Comment by WHomer** [comment]
PR #141
