### ISSUE TITLE
User Story 58, Admin is redirected from User profile to Merchant dashboard

### ISSUE THREAD

**Issue by memcmahon** [BrennanAyers/little_shop#25]
```
As an admin user
If I visit a profile page for a user, but that user is a merchant
Then I am redirected to the appropriate merchant dashboard page.
eg, if I visit "/admin/users/7" but that user is a merchant
Then I am redirected to "/admin/merchants/7"
And I see their merchant dashboard page
```

DO THESE STORIES FIRST:
- User Story 56, Admin User Profile Page
- User Story 38, Admin can see a merchant's dashboard

### Checklist:

- [x] base tests are written
- [x] base code is written to pass tests
- [x] edge case ("sad path") tests written (if required)
- [x] edge case code written (if required)
- [ ] code is reviewed
- [ ] branch is merged
- [ ] all tests still pass

child of #208

child of #274

depends on #206

depends on #228

**Comment by WHomer** [comment]
PR #141
