### ISSUE TITLE
User Story 2, Visitor Navigation

### ISSUE THREAD

**Issue by memcmahon** [BrennanAyers/little_shop#81]
```
As a visitor
I see a navigation bar
This navigation bar includes links for the following:
- a link to return to the welcome / home page of the application ("/")
- a link to browse all items for sale ("/items")
- a link to see all merchants ("/merchants")
- a link to my shopping cart ("/cart")
- a link to log in ("/login")
- a link to the user registration page ("/register")

Next to the shopping cart link I see a count of the items in my cart
```

### Checklist:

- [x] base tests are written
- [x] base code is written to pass tests
- [x] edge case ("sad path") tests written (if required)
- [x] edge case code written (if required)
- [x] code is reviewed
- [x] branch is merged
- [x] all tests still pass

child of #272

child of #274

**Comment by WHomer** [comment]
I moved this to a new issue #94 

`Next to the shopping cart link I see a count of the items in my cart`

**Comment by WHomer** [comment]
I created two new routes, one for merchants#index and one for carts#index.  The carts#show will need to be removed I assume as we learn about carts tomorrow.
